import { auth } from "@clerk/nextjs/server";
import NavbarMain from "~/components/navbars/navbar-main";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { sessionClaims } = auth();

  return (
    <div className="min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-gray-900 via-slate-900 to-black">
      {/* navbar with luxury styling */}
      <div className="border-b border-amber-500/20 bg-black/40 backdrop-blur-xl">
        <div className="mx-auto px-4">
          <NavbarMain role={sessionClaims?.metadata.role} />
        </div>
      </div>

      {/* main content area */}
      <main className="mx-auto min-h-[calc(100vh-4rem)] bg-gradient-to-b from-transparent to-black/50">
        <div className="h-full p-6">{children}</div>
      </main>
    </div>
  );
}
